# from fastapi import FastAPI
# from fastapi.middleware.cors import CORSMiddleware
# import subprocess
# import ollama

# def clean_git_diff(diff: str) -> str:
#     cleaned_lines = []

#     for line in diff.splitlines():

#         # remove metadata noise
#         if line.startswith("index ") or line.startswith("diff --git"):
#             continue

#         if line.startswith("new file mode") or line.startswith("deleted file mode"):
#             continue

#         cleaned_lines.append(line)

#     return "\n".join(cleaned_lines).strip()

# app = FastAPI()

# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["*"],
#     allow_credentials=True,
#     allow_methods=["*"],
#     allow_headers=["*"],
# )

# @app.get("/")
# def home():
#     return {"message": "DevLog API running"}

# @app.get("/git-diff")
# def git_diff():
#     try:
#         result = subprocess.check_output(
#             ["git", "diff", "--cached"],
#             cwd="../"
#         )
#         return {"diff": result.decode("utf-8")}
#     except Exception as e:
#         return {"diff": str(e)}
    
# @app.get("/generate-commit")
# def generate_commit():

#     try:
#         diff = subprocess.check_output(
#             ["git", "diff", "--cached"],
#             cwd="../"
#         ).decode("utf-8")

#         if not diff.strip():
#             return {"message": "chore: no staged changes"}

#         # STEP 1: clean diff
#         cleaned_diff = clean_git_diff(diff)

#         # STEP 2: build prompt
#         prompt = build_commit_prompt(cleaned_diff)

#         # STEP 3: AI call
#         response = ollama.chat(
#             model="mistral",
#             messages=[
#                 {"role": "user", "content": prompt}
#             ]
#         )

#         commit_message = response["message"]["content"].strip()

#         # STEP 4: safety cleanup (very important)
#         commit_message = commit_message.split("\n")[0]

#         return {
#             "message": commit_message,
#             "model": "mistral",
#             "status": "success"
#         }

#     except Exception as e:
#         return {
#             "message": str(e),
#             "status": "error"
#         }
# @app.get("/generate-pr")
# def generate_pr():
#     try:
#         diff = subprocess.check_output(
#             ["git", "diff", "--cached"],
#             cwd="../"
#         ).decode("utf-8")

#         files_changed = []

#         for line in diff.splitlines():
#             if line.startswith("diff --git"):
#                 parts = line.split(" ")
#                 if len(parts) >= 3:
#                     filename = parts[2].replace("a/", "")
#                     files_changed.append(filename)

#         insertions = 0
#         deletions = 0

#         for line in diff.splitlines():
#             if line.startswith("+") and not line.startswith("+++"):
#                 insertions += 1

#             elif line.startswith("-") and not line.startswith("---"):
#                 deletions += 1

#         summary_lines = "\n".join(
#             [f"- Updated `{file}`" for file in files_changed]
#         )

#         pr_text = f"""
# ## Summary

# {summary_lines}

# ## Stats
# - Files changed: {len(files_changed)}
# - Insertions: {insertions}
# - Deletions: {deletions}

# ## Changes
# - Improved project structure
# - Updated source code
# - Generated by DevLog

# ## Testing
# - Local testing completed
# """

#         return {
#             "description": pr_text
#         }

#     except Exception as e:
#         return {
#             "description": str(e)
#         }
# from fastapi import FastAPI
# from fastapi.middleware.cors import CORSMiddleware
# import subprocess
# import ollama

# MODEL = "mistral"

# app = FastAPI()

# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["*"],
#     allow_credentials=True,
#     allow_methods=["*"],
#     allow_headers=["*"],
# )

# def get_staged_diff() -> str:
#     """Get git staged diff safely"""
#     try:
#         return subprocess.check_output(
#             ["git", "diff", "--cached"],
#             cwd="../"
#         ).decode("utf-8")
#     except Exception as e:
#         return ""

# def clean_git_diff(diff: str) -> str:
#     """Remove noise from git diff"""
#     cleaned_lines = []

#     for line in diff.splitlines():

#         if line.startswith("diff --git"):
#             continue
#         if line.startswith("index "):
#             continue
#         if line.startswith("new file mode"):
#             continue
#         if line.startswith("deleted file mode"):
#             continue

#         cleaned_lines.append(line)

#     return "\n".join(cleaned_lines).strip()


# def build_commit_prompt(diff: str) -> str:
#     """Prompt for commit message generation"""
#     return f"""
# You are an expert software engineer.

# Generate a git commit message using Conventional Commits.

# Rules:
# - format: type(scope): message
# - max 80 characters
# - no explanation
# - output ONLY commit message

# Code changes:
# {diff}
# """


# def build_pr_prompt(diff: str) -> str:
#     """Prompt for PR description"""
#     return f"""
# You are an expert software engineer.

# Generate a GitHub Pull Request description.

# Rules:
# - clear summary
# - bullet points for changes
# - include stats if possible
# - professional tone

# Code changes:
# {diff}
# """


# @app.get("/")
# def home():
#     return {"message": "DevLog API running 🚀"}


# @app.get("/git-diff")
# def git_diff():
#     diff = get_staged_diff()
#     return {"diff": diff}


# @app.get("/generate-commit")
# def generate_commit():

#     try:
#         diff = get_staged_diff()

#         if not diff.strip():
#             return {"message": "chore: no staged changes"}

#         cleaned_diff = clean_git_diff(diff)
#         prompt = build_commit_prompt(cleaned_diff)

#         response = ollama.chat(
#             model=MODEL,
#             messages=[{"role": "user", "content": prompt}]
#         )

#         commit_message = response["message"]["content"].strip()
#         commit_message = commit_message.split("\n")[0]

#         return {
#             "message": commit_message,
#             "model": MODEL,
#             "status": "success"
#         }

#     except Exception as e:
#         return {
#             "message": str(e),
#             "status": "error"
#         }


# @app.get("/generate-pr")
# def generate_pr():

#     try:
#         diff = get_staged_diff()

#         if not diff.strip():
#             return {"description": "No staged changes found."}

#         cleaned_diff = clean_git_diff(diff)
#         prompt = build_pr_prompt(cleaned_diff)

#         response = ollama.chat(
#             model=MODEL,
#             messages=[{"role": "user", "content": prompt}]
#         )

#         pr_description = response["message"]["content"].strip()

#         return {
#             "description": pr_description,
#             "model": MODEL,
#             "status": "success"
#         }

#     except Exception as e:
#         return {
#             "description": str(e),
#             "status": "error"
#         }

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import subprocess
import ollama
import time

MODEL = "mistral"  

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

OLLAMA_WARMED = False

def warmup_model():
    """Preload model into memory (removes first-request delay)"""
    global OLLAMA_WARMED

    if not OLLAMA_WARMED:
        try:
            ollama.chat(
                model=MODEL,
                messages=[{"role": "user", "content": "hi"}]
            )
            OLLAMA_WARMED = True
        except:
            pass


def get_staged_diff() -> str:
    """Get git staged diff safely"""
    try:
        return subprocess.check_output(
            ["git", "diff", "--cached"],
            cwd="../"
        ).decode("utf-8")
    except:
        return ""


def clean_git_diff(diff: str) -> str:
    """Reduce noise + LIMIT size for speed"""
    cleaned_lines = []

    for line in diff.splitlines():

        if line.startswith("diff --git"):
            continue
        if line.startswith("index "):
            continue
        if line.startswith("new file mode"):
            continue
        if line.startswith("deleted file mode"):
            continue

        cleaned_lines.append(line)

    cleaned = "\n".join(cleaned_lines).strip()

    return cleaned[:3000]


def build_commit_prompt(diff: str) -> str:
    return f"""
You are an expert software engineer.

Generate a git commit message.

Rules:
- conventional commits format
- max 80 chars
- ONLY output commit message

Code:
{diff}
"""


def build_pr_prompt(diff: str) -> str:
    return f"""
Generate a GitHub PR description.

Rules:
- clear summary
- bullet points
- professional

Code:
{diff}
"""


@app.get("/")
def home():
    return {"message": "DevLog API running 🚀"}


@app.get("/warmup")
def warmup():
    """Call once after server start to make API FAST"""
    warmup_model()
    return {"status": "warmed up"}


@app.get("/git-diff")
def git_diff():
    return {"diff": get_staged_diff()}


@app.get("/generate-commit")
def generate_commit():

    start = time.time()

    try:
        warmup_model()  

        diff = get_staged_diff()

        if not diff.strip():
            return {"message": "chore: no staged changes"}

        diff = clean_git_diff(diff)

        prompt = build_commit_prompt(diff)

        response = ollama.chat(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}]
        )

        commit_message = response["message"]["content"].strip().split("\n")[0]

        return {
            "message": commit_message,
            "time_taken_sec": round(time.time() - start, 2)
        }

    except Exception as e:
        return {"message": str(e)}


@app.get("/generate-pr")
def generate_pr():

    start = time.time()

    try:
        warmup_model()

        diff = get_staged_diff()

        if not diff.strip():
            return {"description": "No staged changes found."}

        diff = clean_git_diff(diff)

        prompt = build_pr_prompt(diff)

        response = ollama.chat(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}]
        )

        return {
            "description": response["message"]["content"].strip(),
            "time_taken_sec": round(time.time() - start, 2)
        }

    except Exception as e:
        return {"description": str(e)}
