from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import subprocess

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def home():
    return {"message": "DevLog API running"}

@app.get("/git-diff")
def git_diff():
    try:
        result = subprocess.check_output(
            ["git", "diff"],
            cwd="../"
        )
        return {"diff": result.decode("utf-8")}
    except Exception as e:
        return {"diff": str(e)}
    
@app.get("/generate-commit")
def generate_commit():
    try:
        result = subprocess.check_output(
            ["git", "diff"],
            cwd="../"
        ).decode("utf-8")

        lines_changed = len(result.splitlines())

        message = f"feat: update project files ({lines_changed} changed lines)"

        return {"message": message}

    except Exception as e:
        return {"message": str(e)}
    
@app.get("/generate-pr")
def generate_pr():
    try:
        result = subprocess.check_output(
            ["git", "diff"],
            cwd="../"
        ).decode("utf-8")

        lines_changed = len(result.splitlines())

        pr_text = f"""
## Summary

- Updated project files
- Modified codebase based on recent changes
- Total changed lines: {lines_changed}

## Notes

Generated by DevLog
        """

        return {"description": pr_text}

    except Exception as e:
        return {"description": str(e)}