from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import subprocess




app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def home():
    return {"message": "DevLog API running"}

@app.get("/git-diff")
def git_diff():
    try:
        result = subprocess.check_output(
            ["git", "diff", "--cached"],
            cwd="../"
        )
        return {"diff": result.decode("utf-8")}
    except Exception as e:
        return {"diff": str(e)}
    
@app.get("/generate-commit")
def generate_commit():
    try:
        diff = subprocess.check_output(
            ["git", "diff", "--cached"],
            cwd="../"
        ).decode("utf-8")

        files_changed = []

        for line in diff.splitlines():
            if line.startswith("diff --git"):
                parts = line.split(" ")
                if len(parts) >= 3:
                    filename = parts[2].replace("a/", "")
                    files_changed.append(filename)

        total_files = len(files_changed)

        if total_files == 0:
            message = "chore: no changes detected"

        elif any("auth" in f.lower() for f in files_changed):
            message = "feat(auth): improve authentication flow"

        elif any("ui" in f.lower() or "component" in f.lower() for f in files_changed):
            message = "feat(ui): update frontend components"

        elif any("api" in f.lower() for f in files_changed):
            message = "feat(api): improve backend endpoints"

        else:
            message = f"feat: update {total_files} project files"

        return {
            "message": message,
            "files_changed": files_changed
        }

    except Exception as e:
        return {"message": str(e)}
    
@app.get("/generate-pr")
def generate_pr():
    try:
        diff = subprocess.check_output(
            ["git", "diff", "--cached"],
            cwd="../"
        ).decode("utf-8")

        files_changed = []

        for line in diff.splitlines():
            if line.startswith("diff --git"):
                parts = line.split(" ")
                if len(parts) >= 3:
                    filename = parts[2].replace("a/", "")
                    files_changed.append(filename)

        insertions = 0
        deletions = 0

        for line in diff.splitlines():
            if line.startswith("+") and not line.startswith("+++"):
                insertions += 1

            elif line.startswith("-") and not line.startswith("---"):
                deletions += 1

        summary_lines = "\n".join(
            [f"- Updated `{file}`" for file in files_changed]
        )

        pr_text = f"""
## Summary

{summary_lines}

## Stats
- Files changed: {len(files_changed)}
- Insertions: {insertions}
- Deletions: {deletions}

## Changes
- Improved project structure
- Updated source code
- Generated by DevLog

## Testing
- Local testing completed
"""

        return {
            "description": pr_text
        }

    except Exception as e:
        return {
            "description": str(e)
        }